name: Test Matrix

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# Permissions for test matrix
permissions:
  contents: read
  checks: write

jobs:
  test-matrix:
    name: Test on ${{ matrix.os }} with Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 21.x]
        exclude:
          # Exclude some combinations to reduce CI time
          - os: windows-latest
            node-version: 18.x
          - os: macos-latest
            node-version: 18.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run
        env:
          NODE_ENV: test

      - name: Build (Ubuntu and macOS only)
        if: matrix.os != 'windows-latest'
        run: npm run build

  # Job to check if all matrix jobs passed
  test-matrix-result:
    name: Test Matrix Result
    runs-on: ubuntu-latest
    needs: test-matrix
    if: always()

    steps:
      - name: Check matrix results
        run: |
          if [ "${{ needs.test-matrix.result }}" != "success" ]; then
            echo "❌ Test matrix failed"
            exit 1
          fi
          echo "✅ All test matrix jobs passed"
